2025-03-08 11:18:07,188 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-08 11:19:08,342 - ERROR - ❌ Exception: unhashable type: 'list'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 94, in __init__
    self.h_mycombi, self.h_combiDict,self.h_criticalMSTypes_criticalMSProjs, self.h_combiExperimentData = generate_combigen(self)
  File "/home/philipp/Projects/INES/INES/src/combigen.py", line 483, in generate_combigen
    getBestChainCombis(self,query, shared, criticalMSTypes, noFilter)
  File "/home/philipp/Projects/INES/INES/src/combigen.py", line 236, in getBestChainCombis
    getBestTreeCombiRec(self,longestPath,query, projection, mylist, [], 0, shared , criticalMSTypes,DistMatrices,MSTrees)
  File "/home/philipp/Projects/INES/INES/src/combigen.py", line 252, in getBestTreeCombiRec
    getBestTreeCombiRec(self,longestPath,query, projection, [], _missingEvents, mycosts, shared, criticalMSTypes,DistMatrices,MSTrees)
  File "/home/philipp/Projects/INES/INES/src/combigen.py", line 288, in getBestTreeCombiRec
    (mycosts, partEvent) = costsOfCombination(self,projection, mycombi, shared, criticalMSTypes,DistMatrices,MSTrees)
  File "/home/philipp/Projects/INES/INES/src/combigen.py", line 308, in costsOfCombination
    mycosts += getSavings(self,partEvent[0], mycombi, projection,DistMatrices,MSTrees)
  File "/home/philipp/Projects/INES/INES/src/combigen.py", line 156, in getSavings
    if partType not in MSTrees:
TypeError: unhashable type: 'list'

2025-03-08 11:19:26,507 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-08 11:20:45,402 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-08 11:23:00,955 - ERROR - ❌ Exception: unhashable type: 'list'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 94, in __init__
    self.h_mycombi, self.h_combiDict,self.h_criticalMSTypes_criticalMSProjs, self.h_combiExperimentData = generate_combigen(self)
  File "/home/philipp/Projects/INES/INES/src/combigen.py", line 483, in generate_combigen
    getBestChainCombis(self,query, shared, criticalMSTypes, noFilter)
  File "/home/philipp/Projects/INES/INES/src/combigen.py", line 236, in getBestChainCombis
    getBestTreeCombiRec(self,longestPath,query, projection, mylist, [], 0, shared , criticalMSTypes,DistMatrices,MSTrees)
  File "/home/philipp/Projects/INES/INES/src/combigen.py", line 252, in getBestTreeCombiRec
    getBestTreeCombiRec(self,longestPath,query, projection, [], _missingEvents, mycosts, shared, criticalMSTypes,DistMatrices,MSTrees)
  File "/home/philipp/Projects/INES/INES/src/combigen.py", line 288, in getBestTreeCombiRec
    (mycosts, partEvent) = costsOfCombination(self,projection, mycombi, shared, criticalMSTypes,DistMatrices,MSTrees)
  File "/home/philipp/Projects/INES/INES/src/combigen.py", line 308, in costsOfCombination
    mycosts += getSavings(self,partEvent[0], mycombi, projection,DistMatrices,MSTrees)
  File "/home/philipp/Projects/INES/INES/src/combigen.py", line 156, in getSavings
    if partType not in MSTrees:
TypeError: unhashable type: 'list'

2025-03-08 11:23:12,339 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-08 11:38:14,981 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-08 11:38:24,917 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-08 11:39:07,178 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-08 11:41:27,720 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-08 11:42:13,026 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-08 11:42:22,903 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-08 11:42:33,132 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-08 11:42:43,081 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-08 11:42:53,044 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-08 11:43:02,552 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-10 19:26:05,336 - ERROR - ❌ Exception: not enough values to unpack (expected 3, got 0)
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 94, in __init__
    self.h_mycombi, self.h_combiDict,self.h_criticalMSTypes_criticalMSProjs, self.h_combiExperimentData = generate_combigen(self)
  File "/home/philipp/Projects/INES/INES/src/combigen.py", line 483, in generate_combigen
    getBestChainCombis(self,query, shared, criticalMSTypes, noFilter)
  File "/home/philipp/Projects/INES/INES/src/combigen.py", line 202, in getBestChainCombis
    partType,MSTrees,DistMatrices = returnPartitioning(self,projection, projection.leafs(), self.h_projrates,criticalMSTypes)
ValueError: not enough values to unpack (expected 3, got 0)

2025-03-10 19:27:27,951 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-10 19:27:36,837 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-10 19:27:45,858 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-10 19:27:55,620 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-10 19:28:05,679 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-10 19:28:15,145 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-10 19:28:25,114 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-10 19:28:35,095 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-10 19:28:44,753 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-10 19:28:53,193 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-10 19:29:01,629 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-10 19:29:15,099 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

2025-03-10 19:29:24,418 - ERROR - ❌ Exception: [Errno 2] No such file or directory: './res/test.csv'
Traceback (most recent call last):
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 125, in <module>
    my_ines = INES(12, 0.5, 6, 0.3, 10, 3, 5, "test")
  File "/home/philipp/Projects/INES/INES/src/INES.py", line 105, in __init__
    with open("./res/"+str(filename)+".csv", "a") as result:
FileNotFoundError: [Errno 2] No such file or directory: './res/test.csv'

